---
title: "MCXpress: RNA-Seq data analysis with Multiple Corespondence Analysis"
author: "Akira Cortal"
date: "`r Sys.Date()`"
output: 
  html_document:
    fig_width: 8
    fig_height: 4
    
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
```{r, include=FALSE}
devtools::load_all("~/MCXpress")
```


## Initialisation of MCXpress object
```{r}
MCX64553 <- Initialise_MCXpress(GSE64553)
MCX64553 <- filter_outlier(MCX64553, percentage = 0.1, threshold = 3)
MCX64553 <- select_most_variable_genes(X = MCX64553, ngenes = 10000)
#MCX64553$ExpressionMatrix
```

## Disjunctive Matrix Creation
In order to analyse the expression matrix with MCA a transformation into a disjunctive matrix is required. The function `Discretisation_Range_01` performs a simple scaling of the expression value from 0 to 1.
```{r}
MCX64553 <- Discretisation_Range_01(MCX64553, scaled = FALSE)
#MCX64553$ExpressionMatrix
```


## Multiple Corespondence Analysis
```{r}
MCX64553 <- MCA(MCX64553)
MCX64553$MCA
MCX64553$MCA$Plot
#MCX64553$Shiny
```


## Clustering
```{r, fig.show='hold'}
MCX64553 <- cluster_kmeans(MCX64553, k = 6)
MCX64553$cluster
MCX64553$cluster$Cluster_Quali
MCX64553$cluster$graph1
```

## GSEA

Performs Geneset enrichmenyt Analysis 

```{r, fig.show='hold'}
MCX64553 <- GSEA(MCX64553, GMTfile = reactome_gmtfile, nperm = 1000)
```
